#pragma once
#include "stdafx.h"
#include "define.h"
#include "MyMain.h"
#include "TEncoding.h"
#include "Core.h"
#include "bass.h"
#include "crc32.h"
#include "Console.h"
#include "TMsgEmulator.h"
#include "CFlamePList.h"
#include "FlameSocketSender.h"
#include <thread>
